version: '3.8'
services:
  local:
    image: postgres:14
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: okawibawa
      POSTGRES_PASSWORD: okaokaoka
      POSTGRES_DB: okapg
    networks:
      - nestpractice
  development:
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: okawibawa
      POSTGRES_PASSWORD: okaokaoka
      POSTGRES_DB: okapg
    networks:
      - nestpractice
networks:
  nestpractice:
